AWSTemplateFormatVersion: '2010-09-09'
Description: Amazon Pinpoint Voice Channel.  This application will place outbound calls triggered by Amazon Pinpoint.  Written in Python3.
Transform: AWS::Serverless-2016-10-31

Parameters:
  PINPOINTLONGCODES:
    Type: String
    Description: Comma delimitted list of Pinpoint Long Codes.


Resources:
  VoiceSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 100
      FifoQueue: true

  PinpointVoiceQueuerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AmazonPinpointVoiceChannel
      CodeUri: voicequeuer/
      Handler: app.lambda_handler
      Runtime: python3.7
      Timeout: 60
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref VoiceSQSQueue
          PINPOINT_LONG_CODES: !Ref PINPOINTLONGCODES
      Policies:
        - Statement:
          - Sid: WriteSQS
            Effect: Allow
            Action: sqs:SendMessage
            Resource: !GetAtt VoiceSQSQueue.Arn


  PinpointVoiceChannelFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AmazonPinpointVoiceChannel-backgrounprocessor
      CodeUri: pinpointvoice/
      Handler: app.lambda_handler
      Runtime: python3.7
      Timeout: 45
      ReservedConcurrentExecutions: 5
      Events:
        VoiceSQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt VoiceSQSQueue.Arn
            BatchSize: 10
      Policies:
        - Statement:
          - Sid: SendVoiceMessage
            Effect: Allow
            Action: sms-voice:SendVoiceMessage
            Resource: !Sub arn:aws:sms-voice:${AWS::Region}:${AWS::AccountId}:/v1/sms-voice/voice/message
          - Sid: PinpointPutEvents
            Effect: Allow
            Action: mobiletargeting:PutEvents
            Resource: !Sub arn:${AWS::Partition}:mobiletargeting:${AWS::Region}:${AWS::AccountId}:*


  PinpointInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref PinpointVoiceQueuerFunction
      Principal: !Sub pinpoint.${AWS::Region}.amazonaws.com
      SourceArn: !Sub arn:${AWS::Partition}:mobiletargeting:${AWS::Region}:${AWS::AccountId}:apps/*

Outputs:
  PinpointVoiceQueuerFunction:
    Description: "A function invoked by an Amazon Pinpoint Campaign or Journey that will place an outbound call to a user"
    Value: !GetAtt PinpointVoiceQueuerFunction.Arn
